/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/demo/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a demo admin token
         * @description **Only when the server runs in demo mode** (the hosted demo). Anywhere else this path doesn't exist, so without a token it answers `401` like any other path.
         *     No token or body needed. The token is an admin token that expires after 1 hour; paste it into **Authorize**.
         *     Demo only: all data is fake and resets every night at 08:00 UTC.
         */
        post: operations["getDemoToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns one page of users in the basic view.
         *     `search` is a partial, case-insensitive match against first name, last name, and email.
         *     Sorting ignores case; ties are broken by first name, then id, always ascending (`order` applies only to the `sort` field). Deleted users are hidden unless `includeDeleted=true`.
         *     A page past the end returns `200` with empty `items` and the real `totalItems` and `totalPages`.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user
         * @description Email must not belong to any user, **including deleted ones** (emails are never reused).
         *     Date of birth must not be in the future, and the user must be 18 or older.
         *     Phones and addresses: 1–3 of each, one per type, exactly one primary (see `UserInput`).
         *     If the server has a user limit and it's reached (deleted users count), the create is refused with `409` and type `/problems/user-limit`.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /**
         * Get one user
         * @description Basic view by default; `view=detailed` adds date of birth, phones, addresses, version, and timestamps.
         */
        get: operations["getUser"];
        /**
         * Update a user (replace)
         * @description Replaces the whole user, including phones and addresses. A phone or address left out is removed permanently.
         *     Same rules as create. Send the `ETag` you loaded in `If-Match`.
         *     A deleted user must be restored before it can be updated.
         */
        put: operations["replaceUser"];
        post?: never;
        /**
         * Delete a user
         * @description Marks the user as deleted; nothing is removed. Their phones and addresses become hidden.
         *     Send the `ETag` you loaded in `If-Match`.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a deleted user
         * @description Brings back the user along with their phones and addresses. Restoring a user who isn't deleted returns `409`.
         */
        post: operations["restoreUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DemoToken: {
            /**
             * @description A JWT with the `admin` role.
             * @example eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYWRtaW4ifQ.signature
             */
            token: string;
            /** @constant */
            tokenType: "Bearer";
            /**
             * @description Seconds until the token stops working.
             * @constant
             */
            expiresIn: 3600;
            /** @example Demo only: all data is fake and resets every night at 08:00 UTC */
            note: string;
        };
        /**
         * Format: uuid
         * @example 3f2a8c1e-7b4d-4e2a-9c6f-1d5e8b7a0c42
         */
        Uuid: string;
        /**
         * Format: date-time
         * @description UTC, ISO 8601.
         * @example 2026-09-12T18:40:00Z
         */
        Timestamp: string;
        /**
         * @description Increments on every change. Also sent as the `ETag` header.
         * @example 3
         */
        Version: number;
        /**
         * @description 1–50 characters after trimming surrounding spaces. Plain English letters (A–Z, a–z),
         *     spaces, hyphens, periods, and the straight apostrophe ('). Must contain at least one letter.
         * @example O'Brien
         */
        PersonName: string;
        /**
         * Format: email
         * @description Unique across all users, including deleted ones. Uniqueness ignores case.
         * @example jose.garcia@example.com
         */
        Email: string;
        /**
         * Format: date
         * @description Date only (`YYYY-MM-DD`). Not in the future; the user must be 18 or older.
         * @example 1990-05-17
         */
        DateOfBirth: string;
        /**
         * @description Unknown fields (such as `id` or `role`) are rejected with `400`.
         * @example {
         *       "firstName": "Jose",
         *       "lastName": "Garcia-Lopez",
         *       "email": "jose.garcia@example.com",
         *       "dateOfBirth": "1990-05-17",
         *       "phones": [
         *         {
         *           "number": "(305) 555-1234",
         *           "type": "mobile"
         *         }
         *       ],
         *       "addresses": [
         *         {
         *           "street": "123 Main St",
         *           "street2": "Apt 4B",
         *           "city": "Miami",
         *           "state": "FL",
         *           "zip": "33101",
         *           "type": "home"
         *         }
         *       ]
         *     }
         */
        UserInput: {
            firstName: components["schemas"]["PersonName"];
            lastName: components["schemas"]["PersonName"];
            email: components["schemas"]["Email"];
            dateOfBirth: components["schemas"]["DateOfBirth"];
            /**
             * @description One per type. A single phone is primary automatically.
             *     With 2–3, exactly one must have `primary: true`. Breaking either rule returns `400`.
             */
            phones: components["schemas"]["PhoneInput"][];
            /**
             * @description One per type. A single address is primary automatically.
             *     With 2–3, exactly one must have `primary: true`. Breaking either rule returns `400`.
             */
            addresses: components["schemas"]["AddressInput"][];
        };
        /**
         * @example {
         *       "id": "3f2a8c1e-7b4d-4e2a-9c6f-1d5e8b7a0c42",
         *       "firstName": "Jose",
         *       "lastName": "Garcia-Lopez",
         *       "email": "jose.garcia@example.com"
         *     }
         */
        UserBasic: {
            id: components["schemas"]["Uuid"];
            firstName: components["schemas"]["PersonName"];
            lastName: components["schemas"]["PersonName"];
            email: components["schemas"]["Email"];
            /** @description When the user was deleted; `null` if active. Only included when `includeDeleted=true`. */
            deletedAt?: components["schemas"]["Timestamp"] | null;
        };
        /**
         * @example {
         *       "id": "3f2a8c1e-7b4d-4e2a-9c6f-1d5e8b7a0c42",
         *       "firstName": "Jose",
         *       "lastName": "Garcia-Lopez",
         *       "email": "jose.garcia@example.com",
         *       "dateOfBirth": "1990-05-17",
         *       "phones": [
         *         {
         *           "number": "+13055551234",
         *           "type": "mobile",
         *           "primary": true
         *         }
         *       ],
         *       "addresses": [
         *         {
         *           "street": "123 Main St",
         *           "street2": "Apt 4B",
         *           "city": "Miami",
         *           "state": "FL",
         *           "zip": "33101",
         *           "type": "home",
         *           "primary": true
         *         }
         *       ],
         *       "version": 1,
         *       "createdAt": "2026-09-12T18:40:00Z",
         *       "updatedAt": "2026-09-12T18:40:00Z"
         *     }
         */
        UserDetailed: components["schemas"]["UserBasic"] & {
            dateOfBirth: components["schemas"]["DateOfBirth"];
            /** @description Primary first, then by type in this order - mobile, home, work. */
            phones: components["schemas"]["Phone"][];
            /** @description Primary first, then by type in this order - home, work, mailing. */
            addresses: components["schemas"]["Address"][];
            version: components["schemas"]["Version"];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        /** @enum {string} */
        PhoneType: "mobile" | "home" | "work";
        /**
         * @example {
         *       "number": "(305) 555-1234",
         *       "type": "mobile",
         *       "primary": true
         *     }
         */
        PhoneInput: {
            /**
             * @description A U.S. number in any common format: `3055551234`, `(305) 555-1234`, `305.555.1234`, `+1 305 555 1234`.
             *     Must be 10 digits (after an optional leading `+1` or `1`); the area code can't start with 0 or 1.
             *     Stored and returned as E.164 (`+13055551234`).
             * @example (305) 555-1234
             */
            number: string;
            type: components["schemas"]["PhoneType"];
            /** @description Optional when it's the only phone (primary automatically). With 2–3 phones, exactly one must be `true`. */
            primary?: boolean;
        };
        Phone: {
            /**
             * @description E.164 format.
             * @example +13055551234
             */
            number: string;
            type: components["schemas"]["PhoneType"];
            /** @example true */
            primary: boolean;
        };
        /** @enum {string} */
        AddressType: "home" | "work" | "mailing";
        /**
         * @description The 50 states, DC, and the territories AS, GU, MP, PR, and VI.
         * @example FL
         * @enum {string}
         */
        UsState: "AL" | "AK" | "AZ" | "AR" | "CA" | "CO" | "CT" | "DE" | "FL" | "GA" | "HI" | "ID" | "IL" | "IN" | "IA" | "KS" | "KY" | "LA" | "ME" | "MD" | "MA" | "MI" | "MN" | "MS" | "MO" | "MT" | "NE" | "NV" | "NH" | "NJ" | "NM" | "NY" | "NC" | "ND" | "OH" | "OK" | "OR" | "PA" | "RI" | "SC" | "SD" | "TN" | "TX" | "UT" | "VT" | "VA" | "WA" | "WV" | "WI" | "WY" | "DC" | "AS" | "GU" | "MP" | "PR" | "VI";
        /**
         * @description Letters, digits, spaces, and `- , .
         * @example 123 Main St.
         */
        AddressText100: string;
        /**
         * @example {
         *       "street": "123 Main St",
         *       "street2": "Apt 4B",
         *       "city": "Miami",
         *       "state": "FL",
         *       "zip": "33101",
         *       "type": "home",
         *       "primary": true
         *     }
         */
        AddressInput: {
            street: components["schemas"]["AddressText100"];
            /**
             * @description Optional (apartment, suite, unit). Omit for none.
             * @example Apt 4B
             */
            street2?: components["schemas"]["AddressText100"];
            /**
             * @description Letters, digits, spaces, and `- , .
             * @example Miami
             */
            city: string;
            state: components["schemas"]["UsState"];
            /**
             * @description Exactly 5 digits; leading zeros kept (e.g. `02134`).
             * @example 33101
             */
            zip: string;
            type: components["schemas"]["AddressType"];
            /** @description Optional when it's the only address (primary automatically). With 2–3 addresses, exactly one must be `true`. */
            primary?: boolean;
        };
        Address: {
            /** @example 123 Main St */
            street: string;
            /**
             * @description `null` if none.
             * @example Apt 4B
             */
            street2: string | null;
            /** @example Miami */
            city: string;
            state: components["schemas"]["UsState"];
            /** @example 33101 */
            zip: string;
            type: components["schemas"]["AddressType"];
            /** @example true */
            primary: boolean;
        };
        UserPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["UserBasic"][];
        };
        PageMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
            /** @example 57 */
            totalItems: number;
            /** @example 3 */
            totalPages: number;
        };
        FieldError: {
            /** @example dateOfBirth */
            field: string;
            /** @example Must be 18 or older */
            message: string;
        };
        /** @description Problem Details (RFC 9457). */
        Problem: {
            /**
             * Format: uri-reference
             * @description Identifies the kind of problem.
             * @example /problems/validation
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem kind.
             * @example Invalid input
             */
            title: string;
            /**
             * @description The HTTP status code.
             * @example 400
             */
            status: number;
            /**
             * @description Explanation specific to this occurrence. Never contains stack traces, SQL, or file paths.
             * @example 2 fields are invalid
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description The request path this problem occurred on.
             * @example /v1/users
             */
            instance?: string;
            /** @description Field-level problems (validation failures only). */
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: {
        /** @description Invalid input. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/validation",
                 *       "title": "Invalid input",
                 *       "status": 400,
                 *       "detail": "2 fields are invalid",
                 *       "instance": "/v1/users",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "message": "Must be a valid email"
                 *         },
                 *         {
                 *           "field": "dateOfBirth",
                 *           "message": "Must be 18 or older"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid, or expired token. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate": components["headers"]["WWWAuthenticate"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/unauthorized",
                 *       "title": "Not signed in",
                 *       "status": 401,
                 *       "detail": "A valid admin token is required"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Valid token, but not an admin. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/forbidden",
                 *       "title": "Not allowed",
                 *       "status": 403,
                 *       "detail": "This operation requires the admin role"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such record, or it is hidden because the user is deleted. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/not-found",
                 *       "title": "Not found",
                 *       "status": 404,
                 *       "detail": "No user with this id"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Breaks a uniqueness rule, or the action doesn't fit the record's state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "A deleted user has this email; restore that user instead"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The `If-Match` version is out of date. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/version-mismatch",
                 *       "title": "Version out of date",
                 *       "status": 412,
                 *       "detail": "This record changed since it was loaded; reload and try again"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request body is over 100 KB. It is refused without being read. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/too-large",
                 *       "title": "Body too large",
                 *       "status": 413,
                 *       "detail": "Request body must be 100 KB or smaller"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The `If-Match` header is missing. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/version-required",
                 *       "title": "Version required",
                 *       "status": 428,
                 *       "detail": "Send the If-Match header with the version you loaded"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "/problems/rate-limited",
                 *       "title": "Too many requests",
                 *       "status": 429,
                 *       "detail": "Rate limit exceeded; retry after 30 seconds"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        UserId: components["schemas"]["Uuid"];
        Page: number;
        PageSize: number;
        /** @description Partial, case-insensitive match against first name, last name, and email. `%` and `_` are plain characters. */
        Search: string;
        Sort: "lastName" | "email";
        Order: "asc" | "desc";
        /** @description `detailed` adds date of birth, phones, addresses, version, and timestamps. */
        View: "basic" | "detailed";
        /** @description Include users marked as deleted. */
        IncludeDeleted: boolean;
        /** @description The `ETag` from when the record was loaded. A stale value returns `412`. */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description The record's current version, quoted. */
        ETag: string;
        /** @description Path of the newly created record. */
        Location: string;
        /** @description Seconds to wait before retrying. */
        RetryAfter: number;
        /** @description How to authenticate. */
        WWWAuthenticate: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDemoToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new admin token. Never cached (`Cache-Control: no-store`). */
            200: {
                headers: {
                    /** @description Always `no-store`, so no browser or proxy keeps a copy of the token. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoToken"];
                };
            };
            /** @description A method other than `POST`. The `Allow` header lists `POST`. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Partial, case-insensitive match against first name, last name, and email. `%` and `_` are plain characters. */
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                /** @description Include users marked as deleted. */
                includeDeleted?: components["parameters"]["IncludeDeleted"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The email is already used, or the server's user limit is reached. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getUser: {
        parameters: {
            query?: {
                /** @description `detailed` adds date of birth, phones, addresses, version, and timestamps. */
                view?: components["parameters"]["View"];
                /** @description Include users marked as deleted. */
                includeDeleted?: components["parameters"]["IncludeDeleted"];
            };
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBasic"] | components["schemas"]["UserDetailed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    replaceUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from when the record was loaded. A stale value returns `412`. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            413: components["responses"]["PayloadTooLarge"];
            428: components["responses"]["PreconditionRequired"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from when the record was loaded. A stale value returns `412`. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            428: components["responses"]["PreconditionRequired"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    restoreUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailed"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
